export const MockResultGithubRepositorySearch = {
  total_count: 1590541,
  incomplete_results: false,
  items: [
    {
      id: 10270250,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
      name: 'react',
      full_name: 'facebook/react',
      private: false,
      owner: {
        login: 'facebook',
        id: 69631,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
        avatar_url: 'https://avatars3.githubusercontent.com/u/69631?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/facebook',
        html_url: 'https://github.com/facebook',
        followers_url: 'https://api.github.com/users/facebook/followers',
        following_url: 'https://api.github.com/users/facebook/following{/other_user}',
        gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
        organizations_url: 'https://api.github.com/users/facebook/orgs',
        repos_url: 'https://api.github.com/users/facebook/repos',
        events_url: 'https://api.github.com/users/facebook/events{/privacy}',
        received_events_url: 'https://api.github.com/users/facebook/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/facebook/react',
      description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
      fork: false,
      url: 'https://api.github.com/repos/facebook/react',
      forks_url: 'https://api.github.com/repos/facebook/react/forks',
      keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/facebook/react/teams',
      hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
      issue_events_url: 'https://api.github.com/repos/facebook/react/issues/events{/number}',
      events_url: 'https://api.github.com/repos/facebook/react/events',
      assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
      branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
      tags_url: 'https://api.github.com/repos/facebook/react/tags',
      blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/facebook/react/languages',
      stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
      contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
      subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
      subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
      commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/facebook/react/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/facebook/react/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
      compare_url: 'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/facebook/react/merges',
      archive_url: 'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
      issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
      pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/facebook/react/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
      releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
      deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
      created_at: '2013-05-24T16:15:54Z',
      updated_at: '2020-09-14T09:29:23Z',
      pushed_at: '2020-09-14T08:31:08Z',
      git_url: 'git://github.com/facebook/react.git',
      ssh_url: 'git@github.com:facebook/react.git',
      clone_url: 'https://github.com/facebook/react.git',
      svn_url: 'https://github.com/facebook/react',
      homepage: 'https://reactjs.org',
      size: 157706,
      stargazers_count: 155816,
      watchers_count: 155816,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 30628,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 571,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 30628,
      open_issues: 571,
      watchers: 155816,
      default_branch: 'master',
      score: 1.0,
    },
  ],
};

export const MockResultGithubRepositoryReleases = [
  {
    url: 'https://api.github.com/repos/facebook/react/releases/24688601',
    assets_url: 'https://api.github.com/repos/facebook/react/releases/24688601/assets',
    upload_url: 'https://uploads.github.com/repos/facebook/react/releases/24688601/assets{?name,label}',
    html_url: 'https://github.com/facebook/react/releases/tag/v16.13.1',
    id: 24688601,
    node_id: 'MDc6UmVsZWFzZTI0Njg4NjAx',
    tag_name: 'v16.13.1',
    target_commitish: 'master',
    name: '16.13.1 (March 19, 2020)',
    draft: false,
    author: {
      login: 'acdlite',
      id: 3624098,
      node_id: 'MDQ6VXNlcjM2MjQwOTg=',
      avatar_url: 'https://avatars0.githubusercontent.com/u/3624098?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/acdlite',
      html_url: 'https://github.com/acdlite',
      followers_url: 'https://api.github.com/users/acdlite/followers',
      following_url: 'https://api.github.com/users/acdlite/following{/other_user}',
      gists_url: 'https://api.github.com/users/acdlite/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/acdlite/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/acdlite/subscriptions',
      organizations_url: 'https://api.github.com/users/acdlite/orgs',
      repos_url: 'https://api.github.com/users/acdlite/repos',
      events_url: 'https://api.github.com/users/acdlite/events{/privacy}',
      received_events_url: 'https://api.github.com/users/acdlite/received_events',
      type: 'User',
      site_admin: false,
    },
    prerelease: false,
    created_at: '2020-03-19T20:02:31Z',
    published_at: '2020-03-19T20:29:38Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/facebook/react/tarball/v16.13.1',
    zipball_url: 'https://api.github.com/repos/facebook/react/zipball/v16.13.1',
    body:
      '### React DOM\r\n\r\n* Fix bug in legacy mode Suspense where effect clean-up functions are not fired. This only affects users who use Suspense for data fetching in legacy mode, which is not technically supported. ([@acdlite](https://github.com/acdlite) in [#18238](https://github.com/facebook/react/pull/18238))\r\n* Revert warning for cross-component updates that happen inside class render lifecycles (`componentWillReceiveProps`, `shouldComponentUpdate`, and so on). ([@gaearon](https://github.com/gaearon) in [#18330](https://github.com/facebook/react/pull/18330))\r\n\r\n## Artifacts\r\n\r\n- react: https://unpkg.com/react@16.13.1/umd/\r\n- react-art: https://unpkg.com/react-art@16.13.1/umd/\r\n- react-dom: https://unpkg.com/react-dom@16.13.1/umd/\r\n- react-is: https://unpkg.com/react-is@16.13.1/umd/\r\n- react-test-renderer: https://unpkg.com/react-test-renderer@16.13.1/umd/\r\n- scheduler: https://unpkg.com/scheduler@0.19.1/umd/',
  },
];
